### PR TITLE
Using new and updated Ap and F10.7 source, removed deprecated indexer.get_loc method

### PR DESCRIPTION
**Pull request by sunipkm**
get_indices() method now retrieves indices from the new source (ftp://ftp.gfz-potsdam.de/pub/home/obs/Kp_ap_Ap_SN_F107/) when the `newsource` input is set (it is set by default).

Replaced dat.index.get_loc() on line 36 of base.py to use the get_indexer method.

### CODE REVIEW

**Comment by petermao** [comment]
I second this PR.  I'm using Sunip's commit now for my work.

This closes issue #6

**Comment by bharding512** [comment]
I third this PR. I say this because [NCAR-GLOW](https://github.com/space-physics/NCAR-GLOW) has geomagindices as a dependency. A fresh install of NCAR-GLOW fails because of the dat.index.get_loc() deprecation

**Comment by rileytroyer** [comment]
I'll also add my support for this. [MSISE00](https://github.com/space-physics/msise00) also has geomagindices as a dependency and fails because of the depreciated pandas.index.get_loc().

**Comment by bharding512** [comment]
Bumping this and adding a new plot comparing geomagindices with @sunipkm's [geomagdata](https://github.com/sunipkm/geomagdata/tree/main), in case it helps anyone as confused as I was. It appears geomagindices only has ~monthly averages for F10.7 in the post-SWPC era.

geomagindices:
image

geomagdata:
image


```
import geomagindices as gm
import pandas as pd

times = pd.date_range('2016-01-01','2024-01-01')
ds_gm = gm.get_indices(times)

plt.figure(figsize=(10,3))
plt.plot(times, ds_gm.f107, 'k-', lw=1)
plt.ylabel('F10.7 index [sfu]')
     
plt.tight_layout()
```

**Pull request closed without merging**
